apiVersion: apps/v1
kind: Deployment
metadata:
  name: venta-aplicacion
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: venta-aplicacion
  replicas: 1 
  template: 
    metadata:
      labels:
        app: venta-aplicacion
    spec:
      containers:      
        - name: venta-aplicacion
          image: calvamej/venta-aplicacion:1.0
          imagePullPolicy: Never
          resources:
            limits:
              memory: 70Mi
              cpu: 100m
            requests:
              memory: 50Mi
              cpu: 50m
          ports:
            - containerPort: 80